packages = [
    "travertino==0.3.0",
]


[files]
#
# invent.
#
"{INVENT}" = "../../src/invent"
#"{INVENT}" = "https://mchilvers.pyscriptapps.com/invent/latest/invent/"
"{INVENT_TO}" = "./invent"
"{INVENT}/__init__.py"="{INVENT_TO}/__init__.py"
"{INVENT}/__about__.py"="{INVENT_TO}/__about__.py"
"{INVENT}/ai.py"="{INVENT_TO}/ai.py"
"{INVENT}/channels.py"="{INVENT_TO}/channels.py"
"{INVENT}/compatability.py"="{INVENT_TO}/compatability.py"
"{INVENT}/datastore.py"="{INVENT_TO}/datastore.py"
"{INVENT}/i18n.py"="{INVENT_TO}/i18n.py"
"{INVENT}/media.py"="{INVENT_TO}/media.py"
"{INVENT}/speech.py"="{INVENT_TO}/speech.py"
"{INVENT}/utils.py"="{INVENT_TO}/utils.py"
#
# invent.ui
#
"{INVENT}/ui/__init__.py"="{INVENT_TO}/ui/__init__.py"
"{INVENT}/ui/app.py"="{INVENT_TO}/ui/app.py"
"{INVENT}/ui/box.py"="{INVENT_TO}/ui/box.py"
"{INVENT}/ui/export.py"="{INVENT_TO}/ui/export.py"
"{INVENT}/ui/page.py"="{INVENT_TO}/ui/page.py"
"{INVENT}/ui/utils.py"="{INVENT_TO}/ui/utils.py"
#
# toga_invent
#
"{TOGA_INVENT}" = "../../src/toga_invent"
"{TOGA_INVENT_TO}" = "./toga_invent"
"{TOGA_INVENT}/__init__.py"="{TOGA_INVENT_TO}/__init__.py"
"{TOGA_INVENT}/app.py"="{TOGA_INVENT_TO}/app.py"
"{TOGA_INVENT}/factory.py"="{TOGA_INVENT_TO}/factory.py"
"{TOGA_INVENT}/resources/toga.png"="{TOGA_INVENT_TO}/resources/toga.png"
"{TOGA_INVENT}/widgets/base.py"="{TOGA_INVENT_TO}/widgets/base.py"
"{TOGA_INVENT}/widgets/box.py"="{TOGA_INVENT_TO}/widgets/box.py"
"{TOGA_INVENT}/widgets/button.py"="{TOGA_INVENT_TO}/widgets/button.py"
"{TOGA_INVENT}/widgets/label.py"="{TOGA_INVENT_TO}/widgets/label.py"
"{TOGA_INVENT}/widgets/textinput.py"="{TOGA_INVENT_TO}/widgets/textinput.py"
"{TOGA_INVENT}/window.py"="{TOGA_INVENT_TO}/window.py"

"https://chaquo.com/public/toga_core-0.4.3.dev427+g45b65b01e.tar.gz" = "./*"
